# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'organizer_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(487, 312)
        self.browseButton = QtWidgets.QPushButton(MainWindow)
        self.browseButton.setGeometry(QtCore.QRect(380, 30, 81, 24))
        self.browseButton.setObjectName("browseButton")
        self.organizeButton = QtWidgets.QPushButton(MainWindow)
        self.organizeButton.setGeometry(QtCore.QRect(160, 60, 111, 24))
        self.organizeButton.setObjectName("organizeButton")
        self.browse_label = QtWidgets.QLineEdit(MainWindow)
        self.browse_label.setGeometry(QtCore.QRect(10, 30, 361, 24))
        self.browse_label.setObjectName("browse_label")
        self.progressBar = QtWidgets.QProgressBar(MainWindow)
        self.progressBar.setGeometry(QtCore.QRect(10, 90, 451, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.windows_dialog = QtWidgets.QLineEdit(MainWindow)
        self.windows_dialog.setGeometry(QtCore.QRect(10, 120, 451, 181))
        self.windows_dialog.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.windows_dialog.setObjectName("windows_dialog")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Files Organizer"))
        self.browseButton.setText(_translate("MainWindow", "&Browse"))
        self.organizeButton.setText(_translate("MainWindow", "Organize Files"))
        self.browse_label.setPlaceholderText(_translate("MainWindow", "browse folder ..."))
        self.windows_dialog.setPlaceholderText(_translate("MainWindow", "starting ..."))
